version: 1
disable_existing_loggers: False

formatters:
  simple:
    datefmt: "%Y-%m-%d %H:%M:%S"
    format: "%(name)s %(asctime)s %(filename)s %(levelname)s: %(message)s"

  general:
    datefmt: "%Y-%m-%d %H:%M:%S"
    format: "%(name)s %(asctime)s %(filename)s %(funcName)s %(levelname)s: %(message)s"

  detail:
    datefmt: "%Y-%m-%d %H:%M:%S"
    format: "%(name)s %(asctime)s %(msecs)d %(filename)s %(funcName)s %(lineno)d %(levelname)s: %(message)s"


handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: detail
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: info.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: errors.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8

loggers:
  my_module:
    level: DEBUG
    handlers: [ console ]
    propagate: no

  my_module_info:
    level: INFO
    handlers: [ info_file_handler ]
    propagate: no

  my_module_error:
    level: ERROR
    handlers: [ error_file_handler ]
    propagate: no

root:
  level: INFO
  handlers: [ console,info_file_handler,error_file_handler ]